### ISSUE TITLE
TNI - Q3 - Gestion des includes 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#1]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/c5030698cb496965f9501c18f746d6a84db6c5aa/NTT/Q3/QUESTION3_TEST1.cpp#L2

`#include <stdio.h>` => est-ce qu'est une instruction en cpp ? + quelle autre "librairie" auriez-vous besoin ? pour répondre au cdc

**Comment by NEZIRITau** [comment]
la librairie <stdio.h>, est une librairie pour le C

```
#include <iostream> 
#include <iomanip>
using namespace std;       // Permet de faciliter le code
```
