### ISSUE TITLE
MCC - Q3 - gestion de cout 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#10]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/d9840f62edce43b811be5c1bf4f2132dbccd718b/MCC/Q3/Question3.cpp#L20

voir commentaire #6 + plus `"%.3"` cette chaine de caractère ne sera pas comprise par le `cout ` sera simplement vue comme des caractères

**Comment by MaelleClerc** [comment]
Cette ligne a été corrigée (maintenant en ligne 23) sur la branche main

**Comment by PBYetml** [comment]
OKI !!
