### ISSUE TITLE
JST - Q5 - Class Triangle 1 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#102]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/57da487ff4de0925c10134ee925697b51d058cce/JST/Q5/Classe%20Triangle.h#L1

voir commentaire #95

**Comment by JonathanETML-ES** [comment]
écriture en majuscule et de nouveau sans le mot classe : 
#ifndef TRIANGLE_H

**Comment by PBYetml** [comment]
OKI
