### ISSUE TITLE
JCA - Q5 - Gestion des fichiers

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#111]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/57da487ff4de0925c10134ee925697b51d058cce/JCA/Q5/Question5_TE1-POBJ_JCA_txt.cpp#L3

pourquoi avoir besoin de la librairie` iostream` ? à quel moment devez-vous déclarer des includes dans un fichier headerfile ?

**Comment by jchafla97** [comment]
Dans un fichier h en cpp j'ai pas besoin de inclure la libraire <iostream>, puisque je n'utilise pas de flux d'entrée ni sortie. Je ne dois en principe èas déclarer des includes dans un fichier headerfile. Cela est à effectuer dans le fichiers sources.

**Comment by PBYetml** [comment]
OKI
