### ISSUE TITLE
JCA - Q5 - Class GenerateurSignal 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#112]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/57da487ff4de0925c10134ee925697b51d058cce/JCA/Q5/Question5_TE1-POBJ_JCA_txt.cpp#L39

Pourquoi avoir besoin des paramètres de la class `Utilisateur `-> quelles sont les liés qu'il y a avec la class `GenerateurSignal `

**Comment by jchafla97** [comment]
En effet, je devais inclure la class utilisateur et pas utiliser les parametres :
Remplacer class Utilisateur par #include "Utilisateur.h", donc :

#ifndef GenerateurSignal_h
#define GenerateurSignal_h

#include "Utilisateur.h"

**Comment by PBYetml** [comment]
Si vous regarder le CDC et le diagramme UML => quel objet devez-vous implémenter dans la class `GenerateurSignal ` => proposer une solution complète de la class

**Comment by jchafla97** [comment]
Je dois implementer premièrement la class signal , voici la proposition :

#ifndef GenerateurSignal_h
#define GenerateurSignal_h

#include "Utilisateur.h"

class Signal;

class GenerateurSignal
{
	public :
		int ChoisirSignal();
		void ChoisirFrequence ();
		void ChoisirAmplitude();

	private: 
		int m_Frequence;
		int m_Amplitude;
	
	public:
    		Signal *mySignal;
    		Utilisateur *myUtilisateur;
}
#endif // GenerateurSignal_h

**Comment by PBYetml** [comment]
voir commentaire fait #113 ... vous mélangez les notions de composition et d'association, voir aussi le commentaire #114

**Comment by jchafla97** [comment]
Suite à des recherches, j'ai enfin compris ce qui allais pas. Voilà la nouvelle proposition : 

#ifndef GenerateurSignal_h
#define GenerateurSignal_h

#include "Signal.h" //cela donne un accès à la déclaration complète de la classe Signal

 //modification
class GenerateurSignal  {
private:
			int m_Frequence;
			int m_Amplitude;
			Signal mySignal; //modification - notion de composition entre Signal et GenerateurSignal

public:
			int ChoisirSignal();
			void ChoisirFrequence ();
			void ChoisirAmplitude ();
                        GenerateurSignal();   // constructeur de l'objet GenerateurSignal
			~GenerateurSignal(); //destructeur de l'objet GenerateurSignal
                 };

**Comment by PBYetml** [comment]
OKI
