### ISSUE TITLE
JCA - Q5 - Class GenerateurSignal1 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#113]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/57da487ff4de0925c10134ee925697b51d058cce/JCA/Q5/Question5_TE1-POBJ_JCA_txt.cpp#L50

Pourquoi avoir besoin de déclarer un objet dynamique de type `Utilisateur ` ? Que vous dit le cdc ?

**Comment by jchafla97** [comment]
Le cdc dit qu'il y a une association entre la class Utilisateur vers la class GenerateurSignal. Donc pas nécessaire de déclarer un objet dynamique ici. Il faut déclarer un objet dynamique de type GenerateurSignal dans la class Utilisateur

**Comment by PBYetml** [comment]
OKI - mais qu'est-ce qui manque dans la class `GenerateurSignal `,  regarder le dernier commentaire #112

**Comment by jchafla97** [comment]
Cela renvoie à ma proposition sur commentaire #112, veuillez aller voir ma correction

**Comment by PBYetml** [comment]
Toujours pas malheureusement, vous mélanger les notion de composition et d'association, cela ne fait pas intervenir les mêmes instructions... vous avez plusieurs instruction à corriger dans votre listing de la class `GenerateurSignal `

**Comment by jchafla97** [comment]
Corrigé dans #112

**Comment by PBYetml** [comment]
OKI
