### ISSUE TITLE
JCA - Q5 - Class Signal 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#114]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/57da487ff4de0925c10134ee925697b51d058cce/JCA/Q5/Question5_TE1-POBJ_JCA_txt.cpp#L63

A quelle class est lié la class Signal (de manière direct) ?

**Comment by jchafla97** [comment]
A la classe Genererateur Signal, donc je dois inclure  :
#include "GenerateurSignal.h"
Puis mettre en public dans ma classe Signal :
public:
    GenerateurSignal myGenerateurSignal;

**Comment by jchafla97** [comment]
Rectification, lien directe avec class GenerateurSignal (notion de composition)
#ifndef Signal_h
#define Signal_h
	
class GenerateurSignal;

**Comment by PBYetml** [comment]
Toujours pas ca !! 

que veut dire : quand vous avez l'instruction suivante dans une class : `class xxx` => en terme d'objet et de lien POO 

même chose pour cette instruction : #inlcude "xxx.h" ? quelles différences entre ces deux instructions ?! 

voir la nouvelle issue #173

**Comment by jchafla97** [comment]
Quand je mets l'instruction class ça veut dire que j'utilise la notion d'association entre class, puis quand je déclare l'include j'utiliser la notion de composition. 

Le lien direct dont vous parlez c'est entre la class Triangle et la class Signal (notion d'héritage)

**Comment by PBYetml** [comment]
OKI
