### ISSUE TITLE
JCA - Q5 - Class Signal 1

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#115]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/57da487ff4de0925c10134ee925697b51d058cce/JCA/Q5/Question5_TE1-POBJ_JCA_txt.cpp#L65

si vous regarder le cdc, et les lignes 67/68, est-ce que la visibilité pour ces deux variables est correctes

**Comment by jchafla97** [comment]
Je devais plutôt utiliser la visibilité protegé :
 protected :
    int m_TableEch[20];
    int m_PeriodeEchantillonage;

**Comment by PBYetml** [comment]
OKI
