### ISSUE TITLE
JCA - Q5 - Class Signal 2

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#116]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/57da487ff4de0925c10134ee925697b51d058cce/JCA/Q5/Question5_TE1-POBJ_JCA_txt.cpp#L70

voir commentaire #114 + que faut-il mettre devant la méthode `CalculerEchantillons`

**Comment by jchafla97** [comment]
Il faut rajouter la notion de virtual, puisque il s'agit d'un polymorphisme, qui se produit lorsqu’il existe une hiérarchie de classes et qu’elles sont liées par héritage.
virtual void CalculerEchantillons ( int Amplitude, int Duty_cycle);

**Comment by PBYetml** [comment]
OKI
