### ISSUE TITLE
JCA - Q5 - Class Triangle 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#117]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/57da487ff4de0925c10134ee925697b51d058cce/JCA/Q5/Question5_TE1-POBJ_JCA_txt.cpp#L82

Pour que la class `Signal `soit comprise dans la class `Triangle`, que faut-il inclure ?

**Comment by jchafla97** [comment]
Je dois rajouter la notion de virtual, me permettant que la classe triangle ait accés à la classe Signal : 
class Triangle : public Signal 
{
	public:

		virtual void CalculerEchantillons(int Amplitude, int DutyCycle);
}

**Comment by PBYetml** [comment]
Non, pour utiliser la class `Signal ` que devez-vous implémenter comme éléments dans la class `Triangle ` ?

**Comment by jchafla97** [comment]
Ups, un oublie, je dois rajouter au début du fichier :
#include "Signal.h"

**Comment by PBYetml** [comment]
OKI
