### ISSUE TITLE
AZI - Q5 - Class GenerateurSignal 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#120]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/57da487ff4de0925c10134ee925697b51d058cce/AZR/Q5/GenerateurSignal.h#L27

qu'apporte la notion de virtuelle (mot clé : `virtual `) au destructeur de la class

**Comment by Ali-Z0** [comment]
Les destructeurs virtuels sont utiles lorsqu'on vas potentiellement supprimer une instance d'une classe dérivée par le biais d'un pointeur vers la classe de base.

**Comment by PBYetml** [comment]
OKI
