### ISSUE TITLE
AZI - Q5 - Class Signal 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#121]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/57da487ff4de0925c10134ee925697b51d058cce/AZR/Q5/Signal.h#L1

Bien que cela ne soit pas faut, attention au nom des define utilisés

**Comment by Ali-Z0** [comment]
L'appeler SIGNAL_H aurait été plus judicieux

**Comment by PBYetml** [comment]
OKI
