### ISSUE TITLE
AZI - Q5 - Class Triangle

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#122]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/57da487ff4de0925c10134ee925697b51d058cce/AZR/Q5/Triangle.h#L10

Pour utiliser l'héritage de la class Signal, qu'avez-vous besoin d'implémenter dans votre code ?

**Comment by Ali-Z0** [comment]
Il manque le :
include "Signal.h"

**Comment by PBYetml** [comment]
OKI
