### ISSUE TITLE
SVE - Q5 - Class Signal 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#127]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/57da487ff4de0925c10134ee925697b51d058cce/SVE/Q5/Fichier/Signal.h#L4

à quoi sert cette librairie ?

**Comment by santivaliante** [comment]
Sous cette forme, à rien HAHAHAH. Je dois donc l'effacer. Nous avons pas besoin d'inclure de fichier .h dans la class Signal.
Erreur non vérifié via Argo UML.

**Comment by PBYetml** [comment]
OKI
