### ISSUE TITLE
CME - Q5 - Class Utilisateur 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#133]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/8d8e0c428902737fc7bf23ac7e15e911287cb016/CME/Q5/Utilisateur.h#L16

Est-ce que le cdc vous demande d’implémenter cet attribut ?

**Comment by Drimvy** [comment]
Non il est pas demandé , je ne sais plus pour quel raison je l'ai mis

**Comment by PBYetml** [comment]
Donc que devez-vous faire avec cette instruction ?

**Comment by Drimvy** [comment]
Je devrais supprimer cette instruction

**Comment by Drimvy** [comment]
Je devrai supprimer L'instruction : int m_CodeFormeChoisie

**Comment by PBYetml** [comment]
OKI
