### ISSUE TITLE
CME - Q5 - Class GenerateurSignal 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#134]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/8d8e0c428902737fc7bf23ac7e15e911287cb016/CME/Q5/GenerateurSignal.h#L5

Si vous relisez le cdc de l'exercice 5, que devez vous implémenter lià à la class `Signal`, comment allez-vous faire cela ?

**Comment by Drimvy** [comment]
il faut implémenter #inculde "Signal.h" car c'est une composition

**Comment by Drimvy** [comment]
Pour finir, il faut déclarer un constructeur et un destructeur pour pouvoir géner son objet dynamique qui est déclarer dans la classe utilisateur

**Comment by PBYetml** [comment]
OKI -> qu'est-ce que cela donnerai en terme de code (listing) ?

**Comment by Drimvy** [comment]
#ifndef GenerateurSignal_h
#define GenerateurSignal_h
#inculde "Signal.h"

class GenerateurSignal {

public:
	
	int ChoisirSignal();
	void ChoisirFrequence();
	void ChoisirAmplitude();
        GenerateurSignal();
        ~GenerateurSignal();

protected:

private:
	int m_Frequence;
	int m_Amplitude;
        Signal Mysignal;
	

};

#endif // GenerateurSignal_h

**Comment by PBYetml** [comment]
OKI
