### ISSUE TITLE
CME - Q5 - Class Signal 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#135]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/8d8e0c428902737fc7bf23ac7e15e911287cb016/CME/Q5/Signal.h#L3

pourquoi inclure la class GenerateurSignal comme librairie ? quelle relation ont ces deux class ?

**Comment by Drimvy** [comment]
Il y a une relation de composition entre ces deux classes.  Cependant c'est la classe Generateursignal qui doit utilisateur la classe signal et non l'inverse donc on va include la classe signal dans le header file Generateursignal, mais nous devons pas include GenerateurSignal.h dans la classe signal

**Comment by PBYetml** [comment]
OKI - donc au niveau instruction que devez-vous faire ?!

**Comment by Drimvy** [comment]
Je dois supprimer cette instruction :  #include "GenerateurSignal.h"

**Comment by PBYetml** [comment]
OKI
