### ISSUE TITLE
CME - Q5 - Class Signal 1

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#136]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/8d8e0c428902737fc7bf23ac7e15e911287cb016/CME/Q5/Signal.h#L10

n'y aurait-il pas un mot clé à mettre devant cette méthode et pourquoi ? 

voir commentaire #130

**Comment by Drimvy** [comment]
c'est du polymorphisme donc il faut ajouter virtual devant la fonction : virtual void  CalculerEchantillons ( int Amplitude, int Duty_cycle);

**Comment by PBYetml** [comment]
OKI
