### ISSUE TITLE
MSS - Q5 - Class Utilisateur 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#137]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/8d8e0c428902737fc7bf23ac7e15e911287cb016/MSS/Q5/Utilisateur.h#L6

Si vous regardez le cdc, quels sont les liens en terme de POO (POBJ) entre la class `GenerateurSignal `et la class `Utilisateur` ?

**Comment by Miguel-SLO** [comment]
Dans ce cas là, il s'agit d'un héritage de la classe GenerateurSIgnal par Utilisateur. Alors que le CDC demandait de réaliser une association. 
Pour cela, il faut alors plutôt utiliser un objet dynamique "GenerateurSignal" dans la classe "Utilisateur".

**Comment by PBYetml** [comment]
et que devez-vous corriger dans cette déclaration de class ?!

**Comment by Miguel-SLO** [comment]
Il faut supprimer l'héritage dans la déclaration de la classe et ajouter un objet dynamique :

GenerateurSignal *myGenerateur;

**Comment by PBYetml** [comment]
OKI
