### ISSUE TITLE
MSS - Q5 - Class Utilisateur

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#138]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/8d8e0c428902737fc7bf23ac7e15e911287cb016/MSS/Q5/Utilisateur.h#L8

voir aussi ligne **9**

en terme de visibilité, comment sont vue ces 2 méthodes

**Comment by Miguel-SLO** [comment]
Comme aucun paramètre de visibilité n'a été spécifié, elles sont mis par défaut dans la visibilité "private".

**Comment by PBYetml** [comment]
est-ce ce qui est demandé par le cdc ?!?

**Comment by Miguel-SLO** [comment]
Je ne vois pas d'indications dans le cdc ?

**Comment by PBYetml** [comment]
effectivement, donc votre approche peut être considérée comme correcte, mais généralement les méthodes d'une class seront plutôt vue comme public (enfin ca dépend du contexte)
