### ISSUE TITLE
MSS - Q5 - Class Generateur 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#139]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/8d8e0c428902737fc7bf23ac7e15e911287cb016/MSS/Q5/GenerateurSignal.h#L6

dans cette déclaration, qu'indiquez-vous en terme de POO (POBJ) quelle relation entre la class GenerateurSignal et la Class Signal -> voir le cdc ?

**Comment by Miguel-SLO** [comment]
Cette ligne indique un héritage de la classe "Signal" . Dans notre cas on souhaitait plutôt avoir une composition, il faut donc supprimer ": private Signal "

**Comment by PBYetml** [comment]
OKI
