### ISSUE TITLE
MSS - Q5 - Class Triangle 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#141]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/8d8e0c428902737fc7bf23ac7e15e911287cb016/MSS/Q5/Triangle.h#L6

En terme de visibilité, comment est perçu la class `Signal`

**Comment by Miguel-SLO** [comment]
Il n'est pas spécifié la manière dont la classe est perçue. Dans notre cas, il faudrait donc rajouter la notion de 'Public' pour que la classe "Triangle" ait accès aux parties publique de la classe "Signal"

**Comment by PBYetml** [comment]
OKI
