### ISSUE TITLE
MCC - Q5 - Class Utilisateur 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#152]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/8d8e0c428902737fc7bf23ac7e15e911287cb016/MCC/Q5/Utilisateur.h#L16

pour que l'objet dynamique soit correctement compris par la class `Utilisateur `que devez-vous implémenter ?

**Comment by MaelleClerc** [comment]
Il faut ajouter un constructeur et un destructeur à la classe GenerateurSignal

**Comment by PBYetml** [comment]
Ce que vous proposer c'est une partie de la correction, mais elle n'est pas complète, qu'est-ce que vous devez déclarer comme instruction pour le fichier headerfile soit complet ??

**Comment by MaelleClerc** [comment]
Il faut inclure GenerateurSignal.h (modifé sur la branche main)

**Comment by PBYetml** [comment]
OKI
