### ISSUE TITLE
MCC - Q5 - Class GenerateurSignal 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#153]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/8d8e0c428902737fc7bf23ac7e15e911287cb016/MCC/Q5/GenerateurSignal.h#L5

Si vous regardez le cdc, qu'est-ce que vous devez implémenter dans cette class 

voir commentaire #146

**Comment by MaelleClerc** [comment]
Pour faire la composition, il faut ajouter le #include <Signal.h>
On ajoute aussi un objet Signal dans les attributs privés

(Le code a été changé dans la branche main)

**Comment by PBYetml** [comment]
OKI
