### ISSUE TITLE
MCC - Q5 - Class Signal 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#154]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/8d8e0c428902737fc7bf23ac7e15e911287cb016/MCC/Q5/Signal.h#L9

Si vous regardez le cdc, n'y a-t-il pas à mettre un mot clé devant cette méthode ? 

voir commentaire #130

**Comment by MaelleClerc** [comment]
Comme la notion d'héritage est utilisée avec la classe Triangle, il faut ajouter le mot clé "virtual"
(Le code a été changé dans la branche main)

**Comment by PBYetml** [comment]
qu'implique la notion de `virtual` en plus de l'héritage ?

**Comment by MaelleClerc** [comment]
Une méthode virtuelle dans une classe parent peut être "modifiée" (réécrite) dans les classes dérivées. Le calcul des échantillons peut ainsi être fait différemment selon la classe enfant qui en hérite. Un peu comme pour une surcharge du constructeur, l'appel sera le même, mais l'effet différent

**Comment by PBYetml** [comment]
OKI
