### ISSUE TITLE
TNI - Q5 - Class Utilisateur 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#155]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/8d8e0c428902737fc7bf23ac7e15e911287cb016/NTT/Q5/Utilisateur.h#L5

voir la ligne **7**, que définissez-vous la class `Utilisateur `ou la class `Generateur ` -> regardez le cdc et surtout le diagramme UML

**Comment by NEZIRITau** [comment]
Je défini la classe Utilisateur. J'ai inversé les termes lors de l'écriture du code. Selon le Cdc :

`class GenerateurSignal;

class Utilisateurs {...}`

**Comment by PBYetml** [comment]
OKI
