### ISSUE TITLE
TNI - Q5 - Class Utilisateur 1

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#156]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/8d8e0c428902737fc7bf23ac7e15e911287cb016/NTT/Q5/Utilisateur.h#L11

voir les lignes **12** et **13**, d’où viennent ces méthodes ? voir le cdc et le diagramme UML

**Comment by NEZIRITau** [comment]
Ces méthodes proviennent de la class  GenerateurSignal

**Comment by PBYetml** [comment]
Que devez-vous faire => proposer une solution complète !!!

**Comment by NEZIRITau** [comment]
Je dois tout d'abord inverser les termes : 

class GenerateurSignal;

class Utilisateur {...}

Et selon le Cdc,  la class Utilisateur doit être comme suit :

```
class Utilisateur {

 public:

    void ConfigurerGenerateur();

    void ObserverSignal();

  public :
	GenerateurSignal *myGenerateurSignal;
};
#endif
```

**Comment by PBYetml** [comment]
OKI
