### ISSUE TITLE
TNI - Q5 - Class GenerateurSignal 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#157]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/8d8e0c428902737fc7bf23ac7e15e911287cb016/NTT/Q5/GenerateurSignal.h#L4

Dans quel cas devez-vous utiliser cette instruction ?!

**Comment by PBYetml** [comment]
Non, votre réponse n'est pas cohérente !!! vous mélangez 3 concepts de POO : association / composition / héritage => dans la class `Generateur ` quels sont les éléments de POO que vous devez mettre en place ?!? => proposez une solution complète !!!

**Comment by NEZIRITau** [comment]
Dans la class GenerateurSignal je dois mettre les éléments suivant :

class Utilisateur association avec GenerateurClass

class GenerateurClass composition avec Signal

**Comment by PBYetml** [comment]
Regardez le diagramme UML => qu'avez-vous fait de faux dans l'implémentation de votre class `GenerateurSignal `

**Comment by NEZIRITau** [comment]
La class GenerateurSignal est comme ceci :

```
#ifndef GenerateurSignal_h
#define GenerateurSignal_h

#include "Signal.h";

class GenerateurSignal {

 public:

        /*
         * Constructeur
	 */

	GenerateurSignal();

	/*
	 * Destructeur
	 */

	virtual ~GenerateurSignal();


    int ChoisirSignal();
    void ChoisirFrequence();
    void ChoisirAmplitude();

 private:
    int m_Frequence;
    int m_Aplitude;

 protected:
    Signal *mySignal;

};

#endif // GenerateurSignal_h
```

**Comment by NEZIRITau** [comment]
L'objet mySignal doit être en private et non en protected

**Comment by PBYetml** [comment]
OKI
