### ISSUE TITLE
TNI - Q5 - Class Signal 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#163]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/8d8e0c428902737fc7bf23ac7e15e911287cb016/NTT/Q5/Signal.h#L17

N'y a-t-il pas un mot clés que vous devez mettre devez cette méthode et pourquoi ?

**Comment by NEZIRITau** [comment]
Oui, le mot clé à mettre devant le code est : virtual

La classe Triangle héritant de la classe Signal, Triangle possède donc la méthode de la classe Signal par héritage

**Comment by PBYetml** [comment]
OKI
