### ISSUE TITLE
ASN - Q5 - Class Utilisateur V02

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#171]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/495f3f8b9a3ca12ae79f48498ce9277ee20db104/ASN/Q5/User.h#L6-L11

selon le cdc, que faut il implémenter dans le class `utilisateur` en terme d'attribut et de méthode => et quelle(s) est/sont la/es relations qu'il y a avec cette class ? 

voir commentaire #70 !!!

**Comment by NotCobaltDragon** [comment]
Association entre la classe User et SignalGenerator

https://github.com/PBYetml/Question_ReponsesEtudiants/blob/8a8638013f847b56b199845eaa838956db384107/ASN/Q5/User.h#L4-L13

**Comment by PBYetml** [comment]
OKI
