### ISSUE TITLE
ASN - Q5 - Class Signal V02

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#172]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/495f3f8b9a3ca12ae79f48498ce9277ee20db104/ASN/Q5/Signal.h#L7

Dans votre nouveau listing, n'y a a-t-il pas quelques chose qui manque devant la méthode `CalculateSamples` ? quelles sont les relations entre la class `signal `et les autres class ?

**Comment by NotCobaltDragon** [comment]
il manque `virtual` avant la méthode

https://github.com/PBYetml/Question_ReponsesEtudiants/blob/3ef274bb1bb11fa17439f466b1fe63503a68f198/ASN/Q5/Signal.h#L7

**Comment by PBYetml** [comment]
OKI
