### ISSUE TITLE
JCA - Q5 - Class Signal V02

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#173]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/93863ac39646ff1b90375a9484d011e078b272b3/JCA/Q5/Question5_TE1-POBJ_JCA_txt.cpp#L56

Avez-vous vraiment besoin de mettre cette instruction ?!? Quel lien avec class `GenerateurSignal `et dans quelle sens ?!?

**Comment by jchafla97** [comment]
Non j'ai pas besoin, puisque il y a une notion de composition de la class Signal vers la class GenerateurSignal. Le lien ce fait donc dans la class GenerateurSignal.

**Comment by PBYetml** [comment]
OKI
