### ISSUE TITLE
SVE - Q3 - Gestion prototype 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#19]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/65ef3e67bac9b343e239e71db71b7ddaf5ed2166/SVE/Q3/QUESTION_3_txt.c#L5

est-ce qu'en C++, y a-t-il des passages par références sous forme de pointeur ? voir commentaire #3

**Comment by santivaliante** [comment]
Il faut remplacer * par &. Le * n'est jamais utilisé.

**Comment by PBYetml** [comment]
OKI
