### ISSUE TITLE
TNI - Q3 - Gestion des includes 2 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#2]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/c5030698cb496965f9501c18f746d6a84db6c5aa/NTT/Q3/QUESTION3_TEST1.cpp#L3

qu'avez-vous fait de faux dans cette instruction ?  :~

**Comment by NEZIRITau** [comment]
J'ai fais une faute de frappe lors de l'écriture de l'algorithme.

#incldue -> #include
