### ISSUE TITLE
SVE - Q3 - Gestion du cout/cin 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#20]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/65ef3e67bac9b343e239e71db71b7ddaf5ed2166/SVE/Q3/QUESTION_3_txt.c#L14

qu'avez-vous oublié de déclarer dans cette instruction - regardez le listing du cdc et le commentaire #6

**Comment by santivaliante** [comment]
Il faut ajouter "cout <<setiosFlages(std::ios::scientific)" pour la notion scientifique. Puis, avoir une précision à 3 chiffre après la virgule. Il faut donc ajouter cout.precision(3).

**Comment by PBYetml** [comment]
OKI
