### ISSUE TITLE
AZR - Q3 - Gestion des includes 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#21]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/2066f5273ee709c4222c8f8c09c9e82c1112dc57/AZR/Q3/Question3.cpp#L2

N'y aurait-il pas quelque chose que vous auriez oubliez pour respecter complètement les cdc voir commentaire #6 & #7

**Comment by Ali-Z0** [comment]
Il manque le :
#include <iomanip> 
Pour permettre de définir la précision des valeurs à virgule flottante

**Comment by PBYetml** [comment]
OK - les crochets sont simple à écrire `<>`
