### ISSUE TITLE
AZR - Q3 - Gestion du cout 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#22]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/2066f5273ee709c4222c8f8c09c9e82c1112dc57/AZR/Q3/Question3.cpp#L19

si vous regardez le listing du cdc, est-ce que vous respectez complètement ce qui est affiché ? voir commentaires #6

**Comment by Ali-Z0** [comment]
Il manque l'affichage à mettre en mode notation scientifique avec la ligne suivante : 
cout << setiosflag(mask: std::ios::scientific);
Il manque aussi la précision des chiffres :
 cout << "Soustraction mode affichage flottant : X - Y = " << cout.precision(prec: 3) << var_f_1 << "-" << var_f_2 << " = " << (var_f_1- var_f_2);

**Comment by PBYetml** [comment]
OKI
