### ISSUE TITLE
JCA- Q3 - Gestion des includes 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#23]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/0b0b41f45e3a420c8d3b6c988829cc51488e982b/JCA/Q3/Question3_TE1-POBJ_JC_txt.cpp#L4

N'y a-t-il pas un élément que vous avez oublié pour respectez complètement le listing du cdc - voir commentaire #7

**Comment by jchafla97** [comment]
#include <iomanip>

**Comment by jchafla97** [comment]
J'ai oublié le <iomanip> :)

**Comment by PBYetml** [comment]
Qu'est-ce que c'est ?! proposez un instruction !!

**Comment by jchafla97** [comment]
//libraire standart
#include <iostream>
using namespace std;
#include <iomanip> //cela me permet d'utiliser le mode scientifique

etc

**Comment by PBYetml** [comment]
OKI - mais ce que je voulais voir le nom dans la libraire que vous devez implémenter `iomanip `

https://github.com/PBYetml/Question_ReponsesEtudiants/blob/e18f4eb64c0128dc070d2fedc0e4626611e2b20a/JCA/Q3/Question3_TE1-POBJ_JC_txt.cpp#L7
