### ISSUE TITLE
JCA - Q3 - Gestion du cin 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#24]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/0b0b41f45e3a420c8d3b6c988829cc51488e982b/JCA/Q3/Question3_TE1-POBJ_JC_txt.cpp#L30

selon votre "écriture" choisie en début de fichier qu'avez-vous oublié devant le cin ?

**Comment by jchafla97** [comment]
J'ai oublié le using namespace std :)

**Comment by PBYetml** [comment]
OKI
