### ISSUE TITLE
JCA - Q3 -  Gestion du cout 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#25]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/0b0b41f45e3a420c8d3b6c988829cc51488e982b/JCA/Q3/Question3_TE1-POBJ_JC_txt.cpp#L21

Attention les opérateur de conversion `%x.yf` ne fonctionne pas avec l'objet cout

**Comment by PBYetml** [comment]
OKI pour l'explication - mais où peut-on voir le code modifié

**Comment by jchafla97** [comment]
cout << setiosflags(ios : : scientific);
cout << "soustraction mode affichage flottant : X - Y = " << cout.precision(3) << var_f_1 << " - " << var_f_2 << " = " << (var_f_1 - var_f_2) << endl;
voilà

**Comment by PBYetml** [comment]
OKI
