### ISSUE TITLE
JST - Q3 -  Gestion des includes 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#29]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/f18d519e214da5f338e74398d82a65f74ed47a3c/JST/Q3/Ex3.cpp#L1

pour respectez le cdc, n'y aurait-il pas quelques chose à implémenter dans les librairies - voir commentaire #21

**Comment by JonathanETML-ES** [comment]
je n'ai pas mis le :
#include <iomanip>
Il me servira pour le nombre flottant afin de fixer ça précision.

**Comment by PBYetml** [comment]
les flèches c'est simplement `< >` :P
