### ISSUE TITLE
TNI - Q3 - Gestion prototype 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#3]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/c5030698cb496965f9501c18f746d6a84db6c5aa/NTT/Q3/QUESTION3_TEST1.cpp#L8

en c++ comment faites-vous un passage par référence ? à quelle occasion utilisez-vous des pointeurs en C++ ?

**Comment by NEZIRITau** [comment]
En C++, au lieu de passer les adresses des variables, il suffit de passer les variables elles-mêmes en utilisant des paramètres sous la forme de références. 

La syntaxe des paramètres devient alors :

type &identificateur (type &identificateur [...])

**Comment by NEZIRITau** [comment]
Comme ceci :

void &Select_Var_Flottant(float &valRetour);

**Comment by NEZIRITau** [comment]
Il sert à aller chercher l'adresse.Veuillez m'excusez, je dois l'écrire de la manière suivante :

void Select_Var_Flottant(float &valRetour);
....
Select_Var_Flottant(var_f_1);  // C'est ici qu'il n'est pas nécessaire de spécifier
Select_Var_Flottant(var_f_2);

**Comment by PBYetml** [comment]
On y arrive :P -> OKI
