### ISSUE TITLE
JST - Q3 -  Gestion appel de fct 1 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#31]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/f18d519e214da5f338e74398d82a65f74ed47a3c/JST/Q3/Ex3.cpp#L10

en c++, est-ce qu'il y a la notion de passage par référence à l'appel de la fct - voir commentaire #5

**Comment by JonathanETML-ES** [comment]
Non, il n'y a pas de passage par référence lors d'un appel de fonction en C++.
Select_var_Flottant(var_f_1); Ceci serrait correct

**Comment by PBYetml** [comment]
OKI
