### ISSUE TITLE
JST - Q3 -  Gestion du cout 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#32]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/f18d519e214da5f338e74398d82a65f74ed47a3c/JST/Q3/Ex3.cpp#L14

qu'est-ce que vous avez omis pour respectez complètement le cdc (voir listing) ? que représente l'opérateur de conversion `%1.3e` `? voir commentaire #6

**Comment by JonathanETML-ES** [comment]
J'ai pas mis le mode natation scientifique à l'affichage donc je devais rajouter ça :
cout << setiosflags(std::ios::scientific);

Je dois aussi venir préciser le nombre après virgule avec ça :

cout << std::setprecision(3) << "soustraction mode affichage flottant : x - y = " << var_f_1 << "-" << var_f_2 << " = " << (var_f_1 - var_f_2) << endl;
