### ISSUE TITLE
GSM - Q3 -  Gestion des includes 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#33]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/823d8ac8577d461a5bd6a7cd19f4d5645aab936e/GSM/Q3/Test1%20POBJ%20question%203_txt.cpp#L5

Ne manque-t-il pas une librairie pour répondre pleinement au cdc ? voir commentaire #7

**Comment by Gajamukan** [comment]
La librairie chaine de caractère  <string.h>

**Comment by Gajamukan** [comment]
La librairie <iomanip>

**Comment by PBYetml** [comment]
OKI -> que va donner cette instruction ?

**Comment by Gajamukan** [comment]
#include <iomanip>  Il va nous permettre d'aligner les valeurs en notation scientifique

**Comment by PBYetml** [comment]
OKI
