### ISSUE TITLE
GSM - Q3 -  Gestion du cout 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#34]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/823d8ac8577d461a5bd6a7cd19f4d5645aab936e/GSM/Q3/Test1%20POBJ%20question%203_txt.cpp#L22

dans cette instruction est-ce que vous répondez pleinement au cdc ? voir commentaire #6

**Comment by Gajamukan** [comment]
Non, il manque la partie notation scientifique
cout << setiosflags (ios :: scientific ) ;
cout.precision (3) ;

**Comment by PBYetml** [comment]
OKI
