### ISSUE TITLE
ASN - Q3 -  Gestion des includes 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#35]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/661c36e303fac9121bb0b60961f079e11d42678a/ASN/Q3/ex3.cpp#L2

pour respectez complètement le cdc que faudrait-il rajouter comme librairie ? voir commentaire #7

**Comment by NotCobaltDragon** [comment]
Solved issue by adding this line:
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/e8c9d0293fafad0845c5eef8e2ac1a63658e0651/ASN/Q3/ex3.cpp#L3

**Comment by PBYetml** [comment]
OKI
