### ISSUE TITLE
ASN - Q3 -  Gestion du prototype fct 1 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#36]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/661c36e303fac9121bb0b60961f079e11d42678a/ASN/Q3/ex3.cpp#L5

est-ce que le passage par référence (écriture en c++) est respecté ? comment faites-vous cela ? voir commentaire #8

**Comment by NotCobaltDragon** [comment]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/62681e3dae4b7756605a334a29a9513d3192ee0c/ASN/Q3/ex3.cpp#L6

**Comment by PBYetml** [comment]
OKI
