### ISSUE TITLE
ASN - Q3 -  gestion déclaration fct 1 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#38]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/661c36e303fac9121bb0b60961f079e11d42678a/ASN/Q3/ex3.cpp#L20

voir commentaire #37 + vous mélangez deux langages (même si ils sont "compatible"), je ne sais pas si le résultat obtenu sera correct + cela ne correspond pas au cdc

**Comment by NotCobaltDragon** [comment]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/62681e3dae4b7756605a334a29a9513d3192ee0c/ASN/Q3/ex3.cpp#L22

**Comment by PBYetml** [comment]
OKI
