### ISSUE TITLE
ASN - Q3 -  Gestion appel de fct 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#39]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/661c36e303fac9121bb0b60961f079e11d42678a/ASN/Q3/ex3.cpp#L12

est-ce un vrai passage par référence (écrit en c++) ? voir commentaire #38 et #27

**Comment by NotCobaltDragon** [comment]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/62681e3dae4b7756605a334a29a9513d3192ee0c/ASN/Q3/ex3.cpp#L13
