### ISSUE TITLE
ASN - Q3 -  Gestion du cout 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#40]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/661c36e303fac9121bb0b60961f079e11d42678a/ASN/Q3/ex3.cpp#L15

dans cette déclaration qu'est-ce qui manque pour répondre complètement au cdc + voir commentaire #6

**Comment by NotCobaltDragon** [comment]
Solved by adding `cout.precision(3)` before all variable output
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/29001e4caf61d6d94fad2ea0c18cc3bf34d28a86/ASN/Q3/ex3.cpp#L16

**Comment by PBYetml** [comment]
OKI
