### ISSUE TITLE
MRI - Q3 -  Gestion des includes

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#43]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/d8bce1d6f52bbea6dec8f66475c13c8a9a9b1198/MRI/Q3/TE1_Q3/main.cpp#L3

Comme vous avez développé la solution sur un IDE, il aurait été bien de placer les **includes** et ensuite de mettre la notion du **namespace** => cette fois, je vous en tiens pas rigueur

**Comment by Belprot** [comment]
Correction : 
#include <iostream>
#include <iomanip>
using namespace std;

**Comment by PBYetml** [comment]
=> vous pouvez écrire de cette manière : 
`#include <iostream>
#include <iomanip>
`
chevron => `<>`
