### ISSUE TITLE
MRI - Q5 - Class utilisteur 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#44]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/d8bce1d6f52bbea6dec8f66475c13c8a9a9b1198/MRI/Q5/Utilisateur.h#L12

Est-ce qu'il y a une méthode nommée sur `newOperation` dans le schéma UML fournit ? ou est-ce que celle-ci est demandé dans le cdc ?

**Comment by Belprot** [comment]
Non, il s'agit sans doute d'un problème venant d'argoUML.

**Comment by PBYetml** [comment]
Donc qu'est-ce que vous devriez faire dans votre listing ?! => correction à apporter ?

**Comment by Belprot** [comment]
Il faut supprimer cette méthode.
