### ISSUE TITLE
MRI - Q5 - class GenerateurSignal 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#45]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/d8bce1d6f52bbea6dec8f66475c13c8a9a9b1198/MRI/Q5/GenerateurSignal.h#L4

Etes-vous sur d'avoir besoin d'implémenter la librairie de classe `Utilisateur` ? Par contre selon le cdc, est-ce que la class `GenerateurSignal` est lié à une autre class ? et comment s'appelle cette **liaison**

**Comment by Belprot** [comment]
Non, il ne faut pas inclure la lib de la classe Utilisateur mais celle de Signal.

**Comment by PBYetml** [comment]
OKI
