### ISSUE TITLE
MRI - Q5 - Class GenerateurSignal 3

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#47]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/d8bce1d6f52bbea6dec8f66475c13c8a9a9b1198/MRI/Q5/GenerateurSignal.h#L21

Je vous en tiendrais pas rigueur mais attention à respectez l'écriture du diagramme, imaginez que vous soyez plusieurs développeurs à sur une même structure.

**Comment by Belprot** [comment]
Effectivement, m_Amplitude; aurait été mieux.
