### ISSUE TITLE
TNI - gestion appel de fct 1 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#5]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/c5030698cb496965f9501c18f746d6a84db6c5aa/NTT/Q3/QUESTION3_TEST1.cpp#L17

Comment se fait un passage par référence en C++ en appel de fct ? voir aussi commentaire #3

**Comment by NEZIRITau** [comment]
En C++,  lors de l'appel de la fonction, il n'est pas nécessaire d'indiquer le pointeur. Le code détecte automatiquement si il va chercher l'adresse ou sa valeur selon l'algorithme écrit.

**Comment by PBYetml** [comment]
comment s'appelle l’instruction de la ligne 17 ? est-ce une déclaration ?

**Comment by NEZIRITau** [comment]
Non, c'est un appel de fonction

**Comment by PBYetml** [comment]
OKI
