### ISSUE TITLE
MRI - Q5 -Gestion Class Signal 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#52]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/d8bce1d6f52bbea6dec8f66475c13c8a9a9b1198/MRI/Q5/Signal.h#L4

Pourquoi avoir besoin d'inclure la libraire de la class` GenerateurSignal` ? quelles sont les relations que la class `Signal` a avec les autres class selon le cdc ?

**Comment by Belprot** [comment]
Il ne faut pas inclure cette lib car la composition va dans l'autre sens.
