### ISSUE TITLE
MRI - Q5 - Class Triangle

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#56]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/d8bce1d6f52bbea6dec8f66475c13c8a9a9b1198/MRI/Q5/Triangle.h#L7

Pourquoi avoir associé deux fois l'héritage de la class `Signal `à la class `Triangle `

**Comment by Belprot** [comment]
Je ne sais pas pourquoi il y a deux fois cette association.
Correction:
ligne 7 :  class Triangle : public Signal {
