### ISSUE TITLE
TNI - Q3 - gestion de cout 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#6]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/c5030698cb496965f9501c18f746d6a84db6c5aa/NTT/Q3/QUESTION3_TEST1.cpp#L24

si vous regardez l'instruction de base en C que vous devez : 
`printf("soustraction mode affichage flottant : X - Y  = %1.3e - %1.3e = %1.3e", var_f_1, var_f_2, (var_f_1 - var_f_2));`

qu'est-ce que vous ne respectez pas ?!

**Comment by NEZIRITau** [comment]
Je respecte pas la condition suivante : %1.3e (Signifie trois décimale après la virgule)


Son équivalent en Cpp est le suivant (using namespace std):

 cout.precision(3);

cout << "Soustraction mode affichage flottant : X - Y  = " << scientific << var_f_1 << " - " << scientific << var_f_2 << " = " << scientific << result;

**Comment by PBYetml** [comment]
dans votre solution proposée  que représente `scientific ` ? etes-vous que c'est cela qu'il faut écrire ?

**Comment by NEZIRITau** [comment]
Selon mes recherches, deux méthodes existent : 

Celle de l'utilisation de cout.precision(3); (en plaçant le cout.precision à la place de scientific)

Ou bien celle du scientific, qui est une méthode venant du header iomanip permettant d'afficher une notation scientifique (dans le cas de l'exercice pas nécessaire je me suis trompé)

**Comment by PBYetml** [comment]
Alors oui il faut l'utiliser, mais la manière dont vous l'écrivez n'est pas correct => la notation scientifique est lié à un flag qu'il faut au non activer avec la méthode `cout `

**Comment by NEZIRITau** [comment]
Il me semble que le flag à activer est le suivant :

`cout<<setiosFlags(std:: ios :: scientific)`

**Comment by PBYetml** [comment]
OKI
