### ISSUE TITLE
MCC - Q3 - gestion des includes 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#7]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/d9840f62edce43b811be5c1bf4f2132dbccd718b/MCC/Q3/Question3.cpp#L2

il manque encore une librairie pour répondre correctement au cdc (notation scientifique)

**Comment by MaelleClerc** [comment]
la libraire iomanip

**Comment by PBYetml** [comment]
effectivement c'est juste et en terme de code (instruction) cela donne quoi ?

**Comment by MaelleClerc** [comment]
Pour l'inclure dans le projet:
#include <iomanip>

Pour utiliser la notation scientifique:
cout << setiosflags(std::ios::scientific);

**Comment by PBYetml** [comment]
vous y répondez dans vos deux commentaires, j'attendais simplement cela : 

`#include <iomanip>`  

;)
