### ISSUE TITLE
ASN - Q5 - Class Utilisateur

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#70]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/57da487ff4de0925c10134ee925697b51d058cce/ASN/Q5/User.h#L4

avant de déclarer la class `User` n'y a-t-il pas quelque chose à mettre avant ? quelle relation à la class` User` avec les autre class ?

**Comment by NotCobaltDragon** [comment]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/495f3f8b9a3ca12ae79f48498ce9277ee20db104/ASN/Q5/User.h#L6-L11

**Comment by PBYetml** [comment]
voir commentaire dans la nouvelle issue #171

**Comment by NotCobaltDragon** [comment]
https://github.com/PBYetml/Question_ReponsesEtudiants/issues/171#issuecomment-1446567888

**Comment by PBYetml** [comment]
OKI
