### ISSUE TITLE
ASN - Q5 - Class Utilisateur 2 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#71]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/57da487ff4de0925c10134ee925697b51d058cce/ASN/Q5/User.h#L10

quelle différence entre un fichier source (cpp) et fichier headerfile (.h), pensez-vous que la déclaration d'une méthode a du sens dans un fichier .h ? + voir ligne 14

**Comment by NotCobaltDragon** [comment]
Le prototype de la méthode doit se trouver dans le fichier `.h` et le code de la méthode doit se trouver dans un fichier `.cpp`

Prototypes:
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/495f3f8b9a3ca12ae79f48498ce9277ee20db104/ASN/Q5/User.h#L9
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/495f3f8b9a3ca12ae79f48498ce9277ee20db104/ASN/Q5/User.h#L10

Méthodes:
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/495f3f8b9a3ca12ae79f48498ce9277ee20db104/ASN/Q5/User.cpp#L3
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/495f3f8b9a3ca12ae79f48498ce9277ee20db104/ASN/Q5/User.cpp#L5

**Comment by PBYetml** [comment]
OKI
