### ISSUE TITLE
ASN - Q5 - Class Utilisateur 3

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#72]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/57da487ff4de0925c10134ee925697b51d058cce/ASN/Q5/User.h#L6

où implémentez-vous la notion de lisibilité dans une class ? + voir ligne 7

**Comment by NotCobaltDragon** [comment]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/495f3f8b9a3ca12ae79f48498ce9277ee20db104/ASN/Q5/User.h#L6-L11

**Comment by PBYetml** [comment]
OKI - mais voir commentaire #171 car la class `utilisateur ` n'est pas correctement implémentée mais vous répondez correctement à la question !
