### ISSUE TITLE
ASN - Q5 - Class GenerateurSignal

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#73]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/57da487ff4de0925c10134ee925697b51d058cce/ASN/Q5/SignalGenerator.h#L4

Quelles sont les relations que la class` GenerateurSignal` a avec les autres class ? voir la donnée du cdc ?!? Ne faut-il pas implémenter quelque chose avant la déclaration de la class

**Comment by NotCobaltDragon** [comment]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/495f3f8b9a3ca12ae79f48498ce9277ee20db104/ASN/Q5/SignalGenerator.h#L4-L14

**Comment by PBYetml** [comment]
votre class n'est pas implémentée complètement => quelle relation y a-t-il avec elle ? il y a des méthodes particulières à implémenter et aussi un attribut particulier, mais lesquels sont-ils ?

**Comment by NotCobaltDragon** [comment]
Il manque le constructeur (`SignalGenerator();`) / destructeur (`~SignalGenerator();`) et le fait que la classe `SignalGenerator` puisse avoir accès à la calsse `Signal` avec `Signal mySignal;`

https://github.com/PBYetml/Question_ReponsesEtudiants/blob/2294bf125722ffaa5fd9f001eac65e12139b82b1/ASN/Q5/SignalGenerator.h#L4-L22

**Comment by PBYetml** [comment]
OKI
