### ISSUE TITLE
ASN - Q5 - Class GenerateurSignal 1 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#74]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/57da487ff4de0925c10134ee925697b51d058cce/ASN/Q5/SignalGenerator.h#L6

Au niveau des attributs n'y a pas quelques choses à indiquer concernant la visibilité ? + est-ce qu'il n'y a que deux attributs ? voir la donnée du cdc ?

**Comment by NotCobaltDragon** [comment]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/495f3f8b9a3ca12ae79f48498ce9277ee20db104/ASN/Q5/SignalGenerator.h#L4-L14

**Comment by PBYetml** [comment]
voir le commentaire #73

**Comment by NotCobaltDragon** [comment]
Résolu normalement dans #73

**Comment by PBYetml** [comment]
OKI
