### ISSUE TITLE
ASN - Q5 - Class GenerateurSignal 2

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#75]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/57da487ff4de0925c10134ee925697b51d058cce/ASN/Q5/SignalGenerator.h#L9

même remarque que pour les attributs concernant la visibilité, voir commentaire #74 + si vous regardez le cdc, quelle relation au niveau POBJ, il y a entre la class `GenerateurSignal` et la class `User` qu'est-ce que vous devriez implémenter aussi

**Comment by NotCobaltDragon** [comment]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/495f3f8b9a3ca12ae79f48498ce9277ee20db104/ASN/Q5/SignalGenerator.h#L4-L14

**Comment by PBYetml** [comment]
voir commentaire #73

**Comment by NotCobaltDragon** [comment]
Résolu normalement dans #73

**Comment by PBYetml** [comment]
OKI
