### ISSUE TITLE
ASN - Q5 - Class Signal 3

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#78]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/57da487ff4de0925c10134ee925697b51d058cce/ASN/Q5/Signal.h#L5

voir la donnée du cdc, quelles sont les relations entre la class `Signal `et les autres class au niveau **POBJ**, que devez-vous implémenter ici au niveau méthode

**Comment by NotCobaltDragon** [comment]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/495f3f8b9a3ca12ae79f48498ce9277ee20db104/ASN/Q5/Signal.h#L4-L17

**Comment by PBYetml** [comment]
voir commentaire #172

**Comment by NotCobaltDragon** [comment]
Je ne comprend pas trop le lien avec #172 et l'issue initiale mais c'est normalement solved dans https://github.com/PBYetml/Question_ReponsesEtudiants/issues/172#issuecomment-1446683350

**Comment by PBYetml** [comment]
voir commentaire en référence à l'issue #76
