### ISSUE TITLE
ASN - Q5 - Class Triangle 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#79]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/57da487ff4de0925c10134ee925697b51d058cce/ASN/Q5/Triangle.h#L8

N'y a-t-il pas une méthode qui manque ?

**Comment by NotCobaltDragon** [comment]
Il manque effectivement une méthode, voici la correction

https://github.com/PBYetml/Question_ReponsesEtudiants/blob/495f3f8b9a3ca12ae79f48498ce9277ee20db104/ASN/Q5/Triangle.h#L9

**Comment by PBYetml** [comment]
OKI
