### ISSUE TITLE
MCC - Q3 - Gestion prototype 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#8]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/d9840f62edce43b811be5c1bf4f2132dbccd718b/MCC/Q3/Question3.cpp#L7

voir commentaire #3 même type d'erreur => passage par référence en c++

**Comment by MaelleClerc** [comment]
Cette ligne a été corrigée (maintenant en ligne 8) sur la branche main

**Comment by PBYetml** [comment]
Top !!!
