### ISSUE TITLE
GSM - Q5 - Class Utilisateur 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#80]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/57da487ff4de0925c10134ee925697b51d058cce/GSM/Q5/Test1%20POBJ%20question%205_txt.cpp#L7

Si vous regardez votre diagramme UML et la flèche que vous avez dessiné quelle impacte cela aura sur votre class `Utilisateur` ? + voir commentaire #70

**Comment by Gajamukan** [comment]
Il faut rajouter la class GenerateurSignal

**Comment by Gajamukan** [comment]
On parle d'association
nous avons un objet dynamique
`GenerateurSignal *myGenerateurSignal;`
