### ISSUE TITLE
GSM - Q5 - Class Utilisateur 1

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#81]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/57da487ff4de0925c10134ee925697b51d058cce/GSM/Q5/Test1%20POBJ%20question%205_txt.cpp#L9

dans la partie visibilité publique de la class `Utilisateur` n'y aurait-il pas quelque chose à implémenter justement du à la flèche de votre diagramme, au niveau attribut

**Comment by Gajamukan** [comment]
```
#ifndef Utilisateur_h
#define Utilisateur_h

class GenerateurSignal;

class Utilisateur {

		public:
			void ConfigurerGenerateur();
			void ObserverSignal ();

		public : 
			GenerateurSignal *myGenerateurSignal;

		};
#endif //Utilisateur_h
```

**Comment by PBYetml** [comment]
OKI
