### ISSUE TITLE
GSM - Q5 - Class GenerateurSignal 1

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#83]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/57da487ff4de0925c10134ee925697b51d058cce/GSM/Q5/Test1%20POBJ%20question%205_txt.cpp#L22

Au niveau méthode, si vous implémentez un relation entre la class `Utilisateur` et la class `Generateur `que devriez-vous implémenter ? voir la donne du CDC pour comprendre la relation ente ces deux class

**Comment by Gajamukan** [comment]
Il faut mettre un constructeur et un destructeur de la class associer
			GenerateurSignal();
			~GenerateurSignal();

**Comment by PBYetml** [comment]
OKI
