### ISSUE TITLE
GSM - Q5 - Class Signal 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#85]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/57da487ff4de0925c10134ee925697b51d058cce/GSM/Q5/Test1%20POBJ%20question%205_txt.cpp#L39

Pensez-vous que votre class `Signal ` est implémentée complètement, selon le diagramme UML et le CDC ?

**Comment by Gajamukan** [comment]
Non, je n'ai malheureusement pas eu le temps de développer ma réponse, mais cette class contient d'autres visibilités que protected et je n'ai pas mis les attributs correspondent à cette classe.

**Comment by PBYetml** [comment]
=> proposer une solution !!!

**Comment by Gajamukan** [comment]
```
#ifndef Signal_h
#define Signal_h

class Signal {
		public:
			virtual void CalculerEchantillons(int Amplitude, int DutyCycle);
			void AfficherEchantillons ();

		private:
			void GetPeriodeEch ();


		protected:
			  int m_TableEch[20];
			  int m_PeriodeEchantillonage;	
		};
#endif //Signal_h
```

**Comment by PBYetml** [comment]
OKI
