### ISSUE TITLE
GSM - Q5 - Class Signal 1

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#86]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/57da487ff4de0925c10134ee925697b51d058cce/GSM/Q5/Test1%20POBJ%20question%205_txt.cpp#L41

Si vous regardez le cdc et le diagramme UML, y a-t-il qu'un paramètre de visibilité pour les attributs et les méthodes de cette class ?

**Comment by Gajamukan** [comment]
Non, selon la donnée la méthode GetPeriodeEch () doit être privée et les attributs sont protected.
Le reste des méthodes sont publics.

**Comment by PBYetml** [comment]
=> proposer une solution complète

**Comment by Gajamukan** [comment]
```
#ifndef Signal_h
#define Signal_h

class Signal {
		public:
			virtual void CalculerEchantillons(int Amplitude, int DutyCycle);
			void AfficherEchantillons ();

		private:
			void GetPeriodeEch ();


		protected:
			  int m_TableEch[20];
			  int m_PeriodeEchantillonage;	
		};
#endif //Signal_h
```

**Comment by PBYetml** [comment]
OKI
