### ISSUE TITLE
GSM - Q5 - Class Triangle 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#87]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/57da487ff4de0925c10134ee925697b51d058cce/GSM/Q5/Test1%20POBJ%20question%205_txt.cpp#L56

Si vous regarder le cdc ainsi que le diagramme UML que vous avez mis à jour, quelle relation a votre class Triangle avec la class Signal en terme de POBJ et que devez-vous implémenter dans cette class ?

**Comment by Gajamukan** [comment]
La relation  est l'héritage 
Il faut ajouter le terme virtual pour la méthode CalculerEchantillons (int Amplitude, int DutyCycle) de la class Signal afin que la class triangle est accès à cette méthode.

**Comment by PBYetml** [comment]
=> proposer une solution concrète !!!

**Comment by Gajamukan** [comment]
`#Include Signal.h `

`class Triangle : public Signal `

**Comment by PBYetml** [comment]
OKI
