### ISSUE TITLE
MCC - Q3 - déclaration de fct 1

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#9]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/d9840f62edce43b811be5c1bf4f2132dbccd718b/MCC/Q3/Question3.cpp#L25

voir commentaire #4 ->gestion passage par référence en c++

**Comment by MaelleClerc** [comment]
Cette ligne a été corrigée (maintenant en ligne 28) sur la branche main

**Comment by PBYetml** [comment]
Top !
