### ISSUE TITLE
JST - Q5 - Class Utilisateur 1

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#90]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/57da487ff4de0925c10134ee925697b51d058cce/JST/Q5/Class%20Utilisateur.h#L19

Qu'est-ce qui ne va pas dans cette déclaration d'objet => comment faîtes vous un déclaration d'objet dynamique en C++ sans instanciation + voir commentaire #89 pour le respect des écritures :~

**Comment by JonathanETML-ES** [comment]
Ce qui est correcte c'est :
GenerateurSignal *myGenerateurSignal;

**Comment by PBYetml** [comment]
OKI
