### ISSUE TITLE
JST - Q5 - Class Utilisateurs 2

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#92]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/57da487ff4de0925c10134ee925697b51d058cce/JST/Q5/Class%20Utilisateur.h#L1

voir commentaire #91 + comment définissez vous une structure du fichier headerfile - attention aux espaces

**Comment by JonathanETML-ES** [comment]
Je devais écrire comme ça pour que ça sois juste :  donc mettre en majuscule
#ifndef UTILISATEUR_H

**Comment by PBYetml** [comment]
OKI
