### ISSUE TITLE
JST - Q5 - Class Signal 

### ISSUE THREAD

**Issue by PBYetml** [PBYetml/Question_ReponsesEtudiants#95]
https://github.com/PBYetml/Question_ReponsesEtudiants/blob/57da487ff4de0925c10134ee925697b51d058cce/JST/Q5/Classe%20Signal.h#L1

voir commentaire #93

**Comment by JonathanETML-ES** [comment]
Je devais écrire en majuscule pour que ça sois juste :
#ifndef SIGNAL_H

**Comment by PBYetml** [comment]
OKI
